### ISSUE TITLE
User avatar center

### ISSUE THREAD

**Issue by Hippyjake** [NoiSek/Aether#1]
Im not sure if you dont want the user avatar off center but the fix is

``` css
        transform: translate(20px, 15px); } /* Change this to */
        transform: translate(16px, 13px); } /* This or something close * /
```

I have forked  this awesome theme and made some small changes to colors, so I won't make a pull request. 
Close if you want  

:v: :neckbeard:
Hippyjake

**Comment by NoiSek** [comment]
Thanks, but the avatar being offcenter within the larger circle is a stylistic choice (worth noting the avatar is still centered within the larger box itself).

**Comment by NelinhoMarinus** [comment]
Hi,

First of all. NICE THEME !! This is the best theme out there.

_Thanks, but the avatar being offcenter within the larger circle is a stylistic choice (worth noting the avatar is still centered within the larger box itself)._

I've noticed that the avatar is centered within the box but is it possible for me to center the avatar background behind the avatar? This is the only thing that's bothering me.

It would make me verry happy to know how this could be done.

Thanks in advance
