### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pms1969** [NoiSek/Aether#10]
Hi,

Just installed the theme on an Antergos system using pacaur.   I use Gnome as my DE.  a little fiddling with the lightdm-webkit2-greeter.conf file had the theme loading fine.  There were just 2 problems.:

- the background_images directive under branding wasn't being honoured
- I couldn't login.  Every time I entered my password, I got a notification drop down saying "Password incorrect, please try again."

I love the theme and would love to have it as my login screen, but not being able to login is a bit of a bummer :-/

If you can point me in the right direction, that would be great.

Cheers,
Paul

**Comment by NoiSek** [comment]
Which `lightdm-webkit-greeter` version do you have installed? This theme hasn't yet begun the rewrite that will make it compatible with the recently released version 3.

As for the background images issue, make sure your wallpaper location is a subdirectory as per:

> Note: This ignores the default value of /usr/share/backgrounds, as this is always set and would prevent the default wallpapers from working. To use wallpapers from within that directory, create a subdirectory at /usr/share/backgrounds/aether (or any other folder name) and change your config value accordingly.

**Comment by pms1969** [comment]
Hi.  Thanks for the response.  Looked through the code last night, but it's going to take a bit more javascript knowledge than I currently have... :-/ 
```
 pacman -Qo /usr/bin/lightdm-webkit2-greeter                                                                                                           Thu 16 Feb 2017 07:19:12 UTC
/usr/bin/lightdm-webkit2-greeter is owned by lightdm-webkit2-greeter 2.2.2-1
```

As for the directory of the wallpaper, it's `/usr/share/backgrounds/user`.  Poking around, I noticed how it was setup, and double checked.  It's `brand` directive is in line with your suggestion.

**Comment by NoiSek** [comment]
Ah, if you're still on version 2 then I can see about pushing a hotfix for you.

Can you post the contents of `/var/log/lightdm/x-0-greeter.log` / `/var/log/lightdm/seat0-greeter.log`?

**Comment by pms1969** [comment]
Happy to do so.  Will need to do so tomorrow tho, as I'll need to start it again to get the logs.  (and I'm out not near my laptop for a while until late tomorrow) :-/

**Comment by pms1969** [comment]
OK, so this is what I get:

x-0.log
```
X.Org X Server 1.19.1
Release Date: 2017-01-11
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.8.14-1-ARCH x86_64
Current Operating System: Linux chulak 4.9.6-1-surfacebook #1 SMP PREEMPT Sat Feb 4 18:45:01 UTC 2017 x86_64
Kernel command line: initrd=\initramfs-linux-surfacebook.img root=UUID=d4470205-c965-4b66-8f6b-1c65a0c74142 rw quiet
Build Date: 14 February 2017  03:36:07AM

Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sun Feb 19 14:51:20 2017
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) libinput bug: Device 'ipts 1B96:005E SingleTouch' does not meet tablet criteria. Ignoring this device.
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
```

I get those `AIGLX` messages after a failed login attempt.

and `seat0-greeter.log`

```
Sun 19 Feb 2017 15:06:23 UTC
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
```

On thing I have noticed is that after a clean reboot, and not just a restart of the display-manager, my first login will work.  locking the machine or restarting the DM then causes the failures, so probably something wrong with the way sessions are read or re-started.

Cheers,
Paul

**Comment by pms1969** [comment]
Here's my `lightdm-webkit2-greeter.conf` as well

```
[greeter]
debug_mode          = false
detect_theme_errors = true
screensaver_timeout = 300
secure_mode         = true
time_format         = LT
time_language       = auto
webkit_theme        = antergos
#webkit_theme        = lightdm-webkit-theme-aether

[branding]
background_images = /usr/share/backgrounds/user
logo              = /usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/arch-logo.png
user_image        = /usr/share/lightdm-webkit/themes/antergos/img/antergos-logo-user.png
```

The `user_image` works fine, but the `background_images` is not :-(

**Comment by pms1969** [comment]
Following on from that. I had lightdm in debug mode last night, and was failing to log in.  I was unfortunately even unable to hit a breakpoint.  Left it running overnight, and returned to it this morning, and first go, was logged in.  Strange behaviour.  I haven't tried locking again, as I've got work to do, but I might experiment a little with the time I leave the screen locked, to see how long it takes before I can log in again.

**Comment by NoiSek** [comment]
So you're able to login, just unable to log back in once the screen has locked?

Are you able to log back in after logging out?

**Comment by NoiSek** [comment]
I'm not certain that the lockscreen issue is one that's fixable from my end, lightdm has a whole host of lockscreen related hurdles that vary from DM to DM. The wallpapers issue, however, is one that I can address.

Previously, the theme would detect non-default values and parse the directory for images, but still attempt to serve them from a local folder. 

I've uploaded a hotfix [here](https://raw.githubusercontent.com/NoiSek/Aether/master/src/js/Aether.js) that should solve the issue. Overwrite the file located at `/usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/js/Aether.js` with this and it should solve the issue.

Do note that in order to actually change the wallpaper, you must click the Distro logo in the top left.

**Comment by pms1969** [comment]
**Logout:** Doesn't allow me back in.  This does work with the default antergos theme.

**Backgrounds: ** now fixed.  Excellent work - Thanks.

The login thing is weird.  I seem to be able to log in very first entry into the system.  But trying to get back in after a screen lock or a logout is mullered.  It would seem that if I log out, then from a terminal, restart the display manager, I can once again log back in.... once.  At which point I'm back to square one.

**Comment by pms1969** [comment]
Actually, not sure what just happened there, but it's back to being completely broken again.  even the backgrounds.  :-(

**Comment by pms1969** [comment]
Am I right in assuming that the Aether.js file is generated from the es6 js files?  if so I think it's being overwritten after use.  If I go back in and change the file again, it works once.... then loses it's way again.

**Comment by NoiSek** [comment]
You are correct, but it isn't ever built on the user-end. Could be cache related?

Are you using / do you have installed more than one DE / WM? After looking through the code, it's possible that the greeter is trying to unlock you into the wrong session if you *first* log into a session other than the default one.

**Comment by pms1969** [comment]
as far as I know, I don't have multiple DE's.  However, having said that, the DE dropdown is duplicated, and contains 2 Gnome's  Gnome Xorg and Gnome Classic.  If I select one of these, I still have the same issue.  but the duplicated drop down disappears.  The dropdown then contains the other Gnome DE and 2 plain Gnome entries.   This supports your theory, although I don't know how to get you any debug info?

**Comment by pms1969** [comment]
Actually, do you have any uncommitted changes to the LoginPanel.jsx?  I'm building locally and copying over the top of it, and it's not letting me log in at all now.

**Comment by NoiSek** [comment]
I've uploaded another hotfix [here](https://github.com/NoiSek/Aether/blob/master/src/js/Aether.js) again for the situation where you're locked out of an existing session, but I don't think it would solve the problem where you're unable to log in after logging out.

If that doesn't solve it, all I can really suggest is that you use another theme for now. Really, definitively fixing the problem is probably best rolled into the existing rewrite, which has been taken up again as of a few days ago.

**Comment by pms1969** [comment]
OK, no luck.  I'll just have to wait.

Thanks for all the help.

**Comment by pms1969** [comment]
well, now discovered that if I have debug mode turned on, and reload, I can pretty reliably login..... go figure.  there has to be something cached somewhere that's bo0rking it.  but that's a happy enough work around for me for the moment.

**Comment by NoiSek** [comment]
Glad to hear it!

**Comment by pms1969** [comment]
Some extra info for your rewrite:  It appears to be a race condition.  I can refresh 10 or more times in a row and it's b0rked, and then all of a sudden, another refresh and it works.  The thing that makes me realise when it's working is that the background from my custom directory is displayed.

Might help with something.  Good luck, it's an excellent theme.
