### ISSUE TITLE
Settings Save File Location?

### ISSUE THREAD

**Issue by ABOhiccups** [NoiSek/Aether#103]
I want to backup my saved settings for Aether Theme. Just in case if I reinstall Arch Linux or install Linux on different computer and want to use the same Aether settings that I use.

Does anyone know where Aether Save Settings File is located at?

**Comment by NoiSek** [comment]
This may or may not answer your question: https://github.com/NoiSek/Aether/issues/58#issuecomment-598723120

**Comment by ABOhiccups** [comment]
Thank you! The Settings Save File was located at /var/lib/lightdm/.local/share/webkitgtk/localstorage/
