### ISSUE TITLE
Background is always black

### ISSUE THREAD

**Issue by WubzyGD** [NoiSek/Aether#110]
**The issue:**

I'm trying to get a background image to show up with aether. I haven't done much of any customization on it other than taking the old backgrounds folder, renaming it to `wallpapers-old`, making a new one, naming it `wallpapers`, and placing one image inside of it. This resulted in a black wallpaper (the rest of Aether works fine, just the wallpaper doesn't).

**What I've tried:**

- I `chmod`ed the folder, then later its file tree, to `777`.
- When that didn't work, I was then told to `chown` it (it was owned by root before). So, I `chown`ed it to my account, `wubzy`. ![Screenshot after `chown`](https://cdn.discordapp.com/attachments/925623461911592980/925669561964040243/unknown.png) (Later doing the same with the folder I wanted, both were tested at this point, neither worked.)
- I tried the default value in `webkit2-greeter.conf` for `background_images`, as well as trying to set it to the Aether wallpapers dir in `src/`. Neither worked. 
![Webkit2 Conf](https://user-images.githubusercontent.com/63122940/147646254-b6306b93-1abb-44a5-926a-a60f6db1592a.png)
- As a last resort after searching through the issues list and seeing the one that dealt with resolution, I realized the image was in 4k, and I'm in 1080p. So I resized the image to standard 1080x1920 with gwenview, rebooted, and it still didn't work.

I'm probably missing some stupidly obvious step. I did follow the guide on this GH's homepage pretty tightly to the letter, and once again, the rest of the greeter works just fine. Thanks for your time!

**Comment by JezerM** [comment]
If your `wallpapers` directory is inside `/home`, `lightdm-webkit2-greeter` and LightDM itself won't allow Aether theme to read your wallpapers. The default `background_images` path is ignored by Aether, so it won't work either. Therefore, you could create a directory at `/usr/share/backgrounds/aether` (or wherever you want), copy your wallpapers, and set `background_images` to your desired path.

If the problem persists, or you do not have your `wallpapers` directory inside `/home`, then provide the log inside `/var/log/lightdm/seat0-greeter.log` (when using lightdm-webkit2-greeter and Aether theme).

**Comment by WubzyGD** [comment]
Thanks! I did exactly as you said and made a folder at /usr/share/backgrounds/aether with one wallpaper in it, changed the background_images variable to that, and still got a black screen.

seat0-greeter.log is also empty.

**Comment by JezerM** [comment]
You could see the issue #111, where seems to be "fixed".

**Comment by WubzyGD** [comment]
See [this comment](https://github.com/NoiSek/Aether/issues/111#issuecomment-1030669699) on a fix.
