### ISSUE TITLE
Black Background when updated background folders with new wallpapers

### ISSUE THREAD

**Issue by D3vil0p3r** [NoiSek/Aether#117]
Hello,
when I remove all default wallpapers and place my new ones in the default folder `/usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/`, after the reboot, the first background image is not shown and the background is black.

If I click on Arch Linux icon, it starts to show the backgrounds. How can this issue be solved?

Furthermore, is there a way to sort wallpapers in the order I prefer?

On `seat0-greeter.log` I don't get any warnings or errors.

UPDATE: I did another test with a clean installation with default wallpapers in the default wallpaper folder. In case I run the login manager, as default the first wallpaper (the car) is shown. If I just rename it as `carb.jpg`, I get again the Black Screen, and I need to click on Arch icon for sliding the wallpapers. If I rename another wallpaper as `car.jpg`, it will appear automatically as the first wallpaper. Could it be that somewhere `car.jpg` is specified in hardcoded manner for being the first appearing wallpaper at the running of LightDM?

**Comment by Vasily59** [comment]
I think you haven't seen the GUI well (just like me). After switching the wallpapers you haven't seen the "save" and the "decline" buttons under the archlinux logo marked as a "check" and a "x" respectively. So after adding your wallpaper you must change to them clicking the archlinux logo and save them clicking the check (no need to eliminate preinstalled ones).

**Comment by D3vil0p3r** [comment]
> I think you haven't seen the GUI well (just like me). After switching the wallpapers you haven't seen the "save" and the "decline" buttons under the archlinux logo marked as a "check" and a "x" respectively. So after adding your wallpaper you must change to them clicking the archlinux logo and save them clicking the check (no need to eliminate preinstalled ones).

If I would like to implement this theme in a new Arch ISO, and I wish the user at the first login gets the custom wallpaper, is there a way to set the first wallpaper by directly change some piece of code/string in the config files of Aether?

**Comment by Vasily59** [comment]
I dont know what to change in the code to make that exactly. But if you save your wallpaper at "/usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/" and start changing themes until you reach the one you added (by clicking the archlinux logo), you can save it clicking the check button under the archlinux logo (where you were clicking to change the theme). If you do so, the theme you have saved will appear the first always.
![save wallpaper screenshot](https://user-images.githubusercontent.com/103695841/194342737-172c631e-8f5b-4292-a62a-82241879cecc.png)

**Comment by D3vil0p3r** [comment]
> I dont know what to change in the code to make that exactly. But if you save your wallpaper at "/usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/" and start changing themes until you reach the one you added (by clicking the archlinux logo), you can save it clicking the check button under the archlinux logo (where you were clicking to change the theme). If you do so, the theme you have saved will appear the first always. ![save wallpaper screenshot](https://user-images.githubusercontent.com/103695841/194342737-172c631e-8f5b-4292-a62a-82241879cecc.png)

So, I think that, after saved the theme as you suggested, I can make a new package with my Aether files and when the user installs the package, it should have already the first custom wallpaper appeared. It should solve my issue. Thanks man!
