### ISSUE TITLE
Password does not work 

### ISSUE THREAD

**Issue by TheSinding** [NoiSek/Aether#12]
Installed it, but it will not accept my password, does it have something to do with gnome ? 

**Lightdm version:** 1.20
**Greeter:** 2.2.3-1
**OS:** Antergos

**Comment by NoiSek** [comment]
Did you manage to solve this on your own?

**Comment by TheSinding** [comment]
For some reason, it kinda solved itself

**Comment by jessemillar** [comment]
I had the same issue just now. A reboot solved it, but annoying nonetheless.
