### ISSUE TITLE
Default Session

### ISSUE THREAD

**Issue by hardal7** [NoiSek/Aether#123]
Trying to change the default desktop session,
#68 doesn't work since the file names got changed.

> The theme attempts to use the user-session value set under your config's [SeatDefaults] when logging in initially, and then defaults to the currently active session if a user is logged in.

**Comment by rubenher55** [comment]
In Archlinux the default session is set by configuration in /usr/lightdm/lightdm.conf that session packages provide. If you need to override this you can set:

[Seat:*]
user-session=name of the session

Where name is the name of the session .desktop file from /usr/share/xsessions/*.desktop.
