### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Viterzgir** [NoiSek/Aether#17]
Can't login in system after logout  it says wrong password.

**Comment by ErwinJoubert** [comment]
Also happens after the computer wakes from sleep.

**Comment by NoiSek** [comment]
This is probably an issue for the upstream [web-greeter](https://github.com/Antergos/web-greeter) / LightDM. LightDM has a few quirks when you use it as a lock screen, it's a semi known issue (and fixable depending on your system). See also: https://github.com/NoiSek/Aether/issues/10#issuecomment-281086917
