### ISSUE TITLE
Failed to start Light Display Manager Error Message

### ISSUE THREAD

**Issue by z2oh** [NoiSek/Aether#22]
When I boot I am met with an error message and cannot see the greeter. This is the error message (apologies for phone picture):
![img_3909](https://user-images.githubusercontent.com/385684/30836635-76fcb21c-a22d-11e7-81b6-0b646829c830.JPG)

When I run the specified command from the image above, I see the following output: 

```
jaday@j-arch-desktop ~> systemctl status lightdm.service
● lightdm.service - Light Display Manager
   Loaded: loaded (/usr/lib/systemd/system/lightdm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-09-25 20:05:51 EDT; 52s ago
     Docs: man:lightdm(1)
  Process: 636 ExecStart=/usr/bin/lightdm (code=exited, status=1/FAILURE)
 Main PID: 636 (code=exited, status=1/FAILURE)
      CPU: 4ms

Sep 25 20:05:50 j-arch-desktop systemd[1]: lightdm.service: Failed with result 'exit-code'.
Sep 25 20:05:51 j-arch-desktop systemd[1]: lightdm.service: Service hold-off time over, scheduling restart.
Sep 25 20:05:51 j-arch-desktop systemd[1]: Stopped Light Display Manager.
Sep 25 20:05:51 j-arch-desktop systemd[1]: lightdm.service: Start request repeated too quickly.
Sep 25 20:05:51 j-arch-desktop systemd[1]: Failed to start Light Display Manager.
Sep 25 20:05:51 j-arch-desktop systemd[1]: lightdm.service: Unit entered failed state.
Sep 25 20:05:51 j-arch-desktop systemd[1]: lightdm.service: Failed with result 'exit-code'.
```

I have followed the troubleshooting in the Readme with no luck. The default lightdm-webkit2-greeter theme works and the gtk greeter works as well. Any ideas? This theme looks awesome and I would love to get it working on my system.

**Comment by NoiSek** [comment]
Were you ever able to troubleshoot this? A newer (v2.0.0) version has just been released that might have fixed your issue.

**Comment by NoiSek** [comment]
I have also found that (only certain versions of?) lightdm interpret comments as part of your config values, and that changing `greeter-session = lightdm-webkit2-greeter #commented-out-theme` in `/etc/lightdm/lightdm.conf` would fix what is probably the same issue you're having.

**Comment by Mugen1991** [comment]
I've got the same problem .

```
DEBUG: Seat seat0: Starting
DEBUG: Seat seat0: Creating greeter session
DEBUG: Seat seat0: Failed to find session configuration lightdm-webkit2-greeter 
DEBUG: Seat seat0: Failed to create greeter session
DEBUG: Failed to start seat
```

my lightdm.conf has the following entry:
`greeter-session = lightdm-webkit2-greeter`

I got the theme in the /etc/lightdm/lightdm-webkit2-greeter.conf set to:
webkit_theme = lightdm-webkit-theme-aether

**Comment by NoiSek** [comment]
Your issue seems unrelated @Mugen1991, you may need to check and make sure that you have a file named `lightdm-webkit2-greeter.desktop` under `/usr/share/xgreeters`. Your system is unable to find the webkit greeter before it ever even gets to the theme.

**Comment by z2oh** [comment]
I installed this theme on another computer (my primary computer now), and everything worked as expected! Beautiful theme, thanks for your work!

**Comment by aytic** [comment]
I had the same issue on Arch and stumbled on that error:
> [+0.01s] DEBUG: XServer 1: Can't launch X server Xephyr, not found in path

You can fix this by adding _DISPLAY=:1_ in /etc/environment
