### ISSUE TITLE
Error loading Aether theme on archlinux

### ISSUE THREAD

**Issue by Adrien-Zemma** [NoiSek/Aether#23]
Hi all,
When I configure my lightdm with Aether theme, I got this: "An error was detected in the current theme that could interfere with the system login process."

This is my lightdm conf: https://pastebin.com/Gw81JshC
My webkit conf: https://pastebin.com/xM1edJuU
Output of "ls -l /usr/share/lightdm-webkit/themes/": https://pastebin.com/38zg63L6

Thanks !

**Comment by NoiSek** [comment]
You will have to rename the theme directory back to `lightdm-webkit-theme-aether`, there are a number of places within the theme that expect to be able to refer directly to this path: `/usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/`

**Comment by Adrien-Zemma** [comment]
Thx it works
