### ISSUE TITLE
[SOLVED] An error detected in the current theme that could interfere with the system login process

### ISSUE THREAD

**Issue by Luisg1** [NoiSek/Aether#24]
Well I was trying some themes for the webkit2-greeter. I came across with yours and I love it! the issue here is that I can make it work :(

I get a black screen and then the text "An error detected in the current theme that could interfere with the system login process". I'm using the default theme for that reason.

I've read some possible issues with their solutions, sadly none of them worked for me. 

I'm fairly new in the linux world, so if I need to send some logs or anything please tell me :)

EDIT: Sorry, I was the one who screwed everything. I was using the wrong package all the time.

**Comment by NoiSek** [comment]
If you could elaborate a little for future users who run into the same error, I'm sure they would appreciate it. Close this when you're ready 👍
