### ISSUE TITLE
How to access the customization dialouge?

### ISSUE THREAD

**Issue by dieggsy** [NoiSek/Aether#25]
It's not entirely clear to me how to acces the customization dialogue from the greeter screen. 

Also, is there an option to _not_ capitalize the username? Cause i'd appreciate that :)

**Comment by NoiSek** [comment]
The customization dialogue should appear when you hover over the bottom left of your screen, it's not visible when not in use. I'll make sure to add an option for capitalization in the next release 👍

**Comment by dieggsy** [comment]
Great, thanks! I found DPI scaling doesn't keep the login centered on my screen, by the way, (and might make the hamburger menu inaccessible?) rendering it kinda useless.

**Comment by LordZane** [comment]
Related question, where is the config file stored?

**Comment by NoiSek** [comment]
@LordZane The config file is stored in webkit-greeter's instance of `localStorage`, which makes it mostly inaccessible to you as a user unless you really, really want to dig for it.

(This is a necessity, the theme has no real way of writing to the filesystem otherwise)

**Comment by NoiSek** [comment]
@dieggsy you should create a separate issue for your DPI centering problems and describe your environment (hardware) and I'll try to see if I can write a patch for it.

**Comment by zjeffer** [comment]
@NoiSek Did you add the option to not capitalize the username yet? I can't find it in the settings menu.
