### ISSUE TITLE
Settings dialog overflows off screen in style settings

### ISSUE THREAD

**Issue by sjclayton** [NoiSek/Aether#27]
Just another small thing -- the settings dialog for style should probably be laid out in a more landscape fashion. 

As on my fairly common resolution laptop (1366x768) the bottom of the dialog is off screen and no matter where I move it I can't get to the bottom of it, and there is no way to resize it that I'm aware of currently.

**Comment by NoiSek** [comment]
This issue isn't really solveable without a significant rewrite, for reasons that are difficult to describe. All I can suggest here is that you use the 'dpi zoom' setting under Style -> Window Appearance to temporarily alter the scale.

The color picker is heavily dependent on an exact set of CSS rules that I can't really change.
