### ISSUE TITLE
Ctrl+A highlights almost everything in login screen

### ISSUE THREAD

**Issue by GUiHKX** [NoiSek/Aether#31]
Minor issue... Whenever I press `Ctrl+A` in the login screen, this happens:

https://i.imgur.com/GbLCYmb.jpg (normal: https://i.imgur.com/8Qg3hSO.jpg)

IMHO, nothing should be highlighted when you press `Ctrl+A` (except user input)

My system:
Arch Linux 64-bit
lightdm-webkit-theme-aether 2.0.1-1

**Comment by GUiHKX** [comment]
Thanks! I don't have much knowledge about CSS but wouldn't it be possible to apply `user-select: none` to all elements, except inputs?

**Comment by NoiSek** [comment]
It's possible to make sure that no element shows the"highlighted" styling with that, but I'm not entirely sure that you can force-select the contents of an input. 

i.e. for a user that does Ctrl+A outside of the password field accidentally it would be strange if it highlighted nothing AND it didn't select the password field text

**Comment by GUiHKX** [comment]
I see... Well, I've been fiddling with the index.html file and I achieved the behavior I wanted by simply adding the `noselect` class to the `<html>` element. `Ctrl+A` still works, but only when the focus in on the password field. Anyway, that's probably not the behavior you're looking for, so it's totally fine for me if you don't change it. :stuck_out_tongue_closed_eyes:
