### ISSUE TITLE
Missing background images

### ISSUE THREAD

**Issue by super-cooper** [NoiSek/Aether#33]
Installed the theme and decided to test it out before I customize it. It loads perfectly, which is great, but it none of the included background images show up, nor do the customization options previewed in the readme. Clicking the logo doesn't make the logos show up. Running it in debug mode shows the following:

```
** (WebKitWebProcess:16075): WARNING **: Unable to determine socket to daemon

** (WebKitWebProcess:16075): WARNING **: Unable to determine socket to daemon

** (WebKitWebProcess:16075): CRITICAL **: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
```

I know nothing about JavaScript, or front end in general, so I'm not really sure what to make of these messages. 

The greeter looks like this in its current configuration:

![greeter_broken](https://user-images.githubusercontent.com/14908880/38781306-afd21b50-40b0-11e8-973b-2eb1129e8801.png)

(I deleted my name from the image, but it looks as you would expect)

I'm working on Debian, if it helps.

EDIT: After a restart, it appears the customization menu is opening, which is great! But the background images still aren't showing up.

**Comment by super-cooper** [comment]
@NoiSek This could be an issue. How can I guarantee the daemon runs with root access at startup?

**Comment by super-cooper** [comment]
@NoiSek Sorry to bother you again but I can't seem to figure out the problem. Permissions on the wallpapers folder are the same as the src folders, which are working fine.

**Comment by NoiSek** [comment]
[This is the default wallpaper directory](https://github.com/NoiSek/Aether/blob/master/src/es6/Logic/FileOperations.js#L16), is this where your theme is installed?

Given all of your other images load, this is probably the cause.

Also note the line above it, which prevents backgrounds from loading if the 'branding' setting in lightdm's config is set to the stock value of `/usr/share/backgrounds`.

**Comment by super-cooper** [comment]
Everything appears to be in order there

![screenshot from 2018-04-19 16-00-00](https://user-images.githubusercontent.com/14908880/39015240-c4a03cbe-43ea-11e8-80ee-ed08c749449d.png)

**Comment by super-cooper** [comment]
It is also only showing the option to sleep when I log out, but all of the other menu options are available when I turn on the computer after a shutdown. Hmmm...

**Comment by NoiSek** [comment]
The Shutdown / Hibernate / Sleep / Restart options are based on the authorized permissions of the user running the greeter at the time, so if that's the case then there's another indicator that what you're dealing with is a permissions issue, but that's still just speculation.

Are you able to run other themes without issue? And are both your lightdm and lightdm-webkit-greeter instances up to date with the upstream versions?

**Comment by super-cooper** [comment]
A couple things:

1. After those three menu options disappeared when I locked the computer using Ctrl+Alt+L, I have tried it again and they don't appear to be missing anymore, which is good but strange.

2. I tried [Litarvan's theme](https://github.com/Litarvan/lightdm-webkit-theme-litarvan) and it wouldn't load at all (it asked me to use the default theme, which worked). This is sounding a lot like a permissions issue, but how can I guarantee that everything runs at the right level (or better yet, why do some things load and others not? The CSS files, and the logo file (which I edited) are clearly being loaded perfectly, but for some reason the wallpapers aren't?) Is this an issue with the permissions I have for your theme specifically, or the actual webkit greeter program?

**Comment by NoiSek** [comment]
The strange thing about that solution is that if it loads then that means it probably isn't a permissions issue, but that LightDM is returning the wrong list of files when the theme asks for them. Some kind of disk caching issue? Not sure what's going on there.

**Comment by super-cooper** [comment]
I have absolutely no idea. These kinds of things only ever happen to me.

**Comment by jarrard** [comment]
Hmm, I think this bug/issue still exists, tried also lightdm and lightdm-git on the arch/aur repo and while I can set the default background fine, I can't see any icon for selecting other backgrounds. 

The customization icon appears down the bottom left of screen but there should be a little icon at top right for backgrounds, shrug.

**Comment by NoiSek** [comment]
If you're saying that you're unsure of how to change your background, that's a separate issue from this one. You would click the distro logo to cycle through all of the backgrounds present.

**Comment by jarrard** [comment]
I can change the background by replacing the original background png in the theme folder. But the selector is not there, its just a default setting.
