### ISSUE TITLE
Settings not loaded (hidpi)

### ISSUE THREAD

**Issue by geyslan** [NoiSek/Aether#35]
HiDPI value is stored but the greeter isn't resized using the scale factor after a reboot. It demands intervention every login.

The last chosen session isn't saved too.

**Comment by NoiSek** [comment]
Resolved in ea19827d80a240bf1195408c2d80b92c2e652a3b

**Comment by geyslan** [comment]
Thanks. It still doesn't persist the last session chosen.

**Comment by NoiSek** [comment]
The last used session isn't managed by the theme itself and relies on whatever value LightDM tells it to use, so I would test this with a separate theme to verify that it isn't an environment issue first. 

If it is isolated to this theme, feel free to open it again as a separate issue.
