### ISSUE TITLE
User Avatar not appearing.

### ISSUE THREAD

**Issue by MatthewMcConnell** [NoiSek/Aether#41]
The user avatar image should show in the circle.

However no avatar seems to show up. I have tried to switch it on and off in the settings as well as trying to set my own .face image which works in kde as it shows up as my avatar. However despite this, nothing works.

**Comment by michaelKurowski** [comment]
+1

**Comment by reliefs** [comment]
+1

**Comment by franciscocpg** [comment]
My Fix: https://github.com/NoiSek/Aether/issues/14#issuecomment-426979496

**Comment by reliefs** [comment]
> My Fix: [#14 (comment)](https://github.com/NoiSek/Aether/issues/14#issuecomment-426979496)

Thanks this fix did work for me also.

**Comment by MatthewMcConnell** [comment]
The fix also worked for me.
