### ISSUE TITLE
Avatar doesn't load

### ISSUE THREAD

**Issue by moonrisewarrior** [NoiSek/Aether#52]
Hello,

I've been trying to get Avatars working with this theme for quite a while now, and I still don't know how to fix it. Right now, my user avatar shows up as some white area behind the background. I have tried creating a .face file, editing AccountsService (pointing to various locations in /home  /var, and otherwise), as well as both of those at once, but it seems that no matter what I do, the theme thinks that my avatar is nonexistent.

I tried selecting the avatar in the "inspect element" tool in debug mode, and doing {element}.src on it, and it seems that it has no source. 

It could be some bug or quirk in the JS I guess, but unfortunately the code for this theme seems to be written in some weird way that I can't understand. 

I've tried setting user_image in the [branding] section of lightdm-webkit2-greeter.conf as well, no effect. 

Is there anything I can do to diagnose/fix this?

Thanks.

**Comment by moonrisewarrior** [comment]
Also, it seems that any edits I make in /src/css or /srs/sass don't ever get applied. Tried clearing lightdm cache. Nothing.

**Comment by NoiSek** [comment]
You might have some success trying [this solution](https://github.com/NoiSek/Aether/issues/14#issuecomment-426979496).

**Comment by moonrisewarrior** [comment]
Okay, thank you, that seems like it could very likely work. I have currently just added a custom script that sets the avatar image with CSS on lightdm load, and that seems to work fine for now, albeit a little hacky, but I'll try this later when I have time, and let you know if it doens't work. Closing issue for now though.
