### ISSUE TITLE
How to set an initial background?

### ISSUE THREAD

**Issue by d3signr** [NoiSek/Aether#55]
Hey,

Love this theme but, on first load i have a white background, no image is displayed until i click the distribution logo. Then it will cycle the backgrounds as expected.

Is there a way to set an initial background? And if not how can i resolve this behaviour since it detracts from what is otherwise, imo, one of the best themes available at present?

Thank you

**Comment by NoiSek** [comment]
Is the issue persistent no matter which wallpaper you save as the default? And are you using only the default wallpapers?

**Comment by d3signr** [comment]
> Is the issue persistent no matter which wallpaper you save as the default? And are you using only the default wallpapers?

Persistent if i change the images in the wallpapers folder but once I click the distribution logo to cycle them, it then works properly, surviving reboots etc. I am not using the default wallpapers, mine are numbered 0001.jpg etc for a series of about six images. 

Thanks
