### ISSUE TITLE
Permission denied (publickey) Fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by StarrKiss** [NoiSek/Aether#59]
Trying to install on Kubuntu, followed the guide:
git clone git@github.com:NoiSek/Aether.git

It gives me those errors.

**Comment by NoiSek** [comment]
If you haven't configured git locally, you'll have to use `git clone https://github.com/NoiSek/Aether.git` instead.

**Comment by StarrKiss** [comment]
That worked, but when I try to run

sudo sed -i 's/^\(#?greeter\)-session\s*=\s*\(.*\)/greeter-session = lightdm-webkit2-greeter #\1/ #\2g' /etc/lightdm/lightdm.conf

To get lightdm set up, it gives a no such file or directory error.

**Comment by StarrKiss** [comment]
And when I boot back up into lightdm, it uses the default theme

**Comment by StarrKiss** [comment]
This error is also given:

sed: -e expression #1, char 81: invalid reference \1 on `s' command's RHS

**Comment by StarrKiss** [comment]
it alternates between errors

**Comment by NoiSek** [comment]
Duplicates #60
