### ISSUE TITLE
Default session

### ISSUE THREAD

**Issue by DurhamDecLab** [NoiSek/Aether#68]
Hi, great theme, it looks really good. Is it possible to set the desktop session as a default, either one you always want or the last one used? Apologies if there is a way to do this that I've missed.

**Comment by NoiSek** [comment]
The theme attempts to use the `user-session` value set under your config's `[SeatDefaults]` when logging in initially, and then defaults to the currently active session if a user is logged in.

See: https://wiki.ubuntu.com/LightDM#Configuration

**Comment by DurhamDecLab** [comment]
Thanks for the response, that's very helpful.
