### ISSUE TITLE
Enable changing which monitor is used

### ISSUE THREAD

**Issue by Krutonium** [NoiSek/Aether#77]
**Is your feature request related to a problem? Please describe.**
The greeter displays on my leftmost monitor

**Describe the solution you'd like**
Ideally, the center monitor should be used

**Describe alternatives you've considered**
I've tried to fix it using the xrandr commands suggested elsewhere, but that didn't work. I've also checked the config file for this theme and there wasn't a way to set it there, either.

**Comment by NoiSek** [comment]
There isn't actually a way for a theme to configure this, you need to configure this upstream higher in the chain at the `lightdm` config level.

Assuming you haven't already seen it, you should do something like this:
https://askubuntu.com/a/862286

But either way, this isn't an issue I can fix.

**Comment by Krutonium** [comment]
`lightdm-gtk-greeter` in the post that you linked is in the same position as you - and it does have the option?

**Comment by NoiSek** [comment]
To be more clear there, you would have to try adding that to the `lightdm-webkit2-greeter.conf` and hope that it works. 

This theme is built on a _subset_ of functionality exposed by the base `lightdm-webkit2-greeter`, meaning that no change made at this level can alter the rendering output in the way that the GTK greeter can.

**Comment by Krutonium** [comment]
I still can't find a way to make this work the way it should, and so far as I can tell, the original lightdm-webkit2-greeter was a Antergos (RIP) Project, which means it's dead.
