### ISSUE TITLE
Use "lightdm-webkit-theme-aether-git" from the AUR

### ISSUE THREAD

**Issue by GoDzM4TT3O** [NoiSek/Aether#78]
**Is your feature request related to a problem? Please describe.**
`lightdm-webkit-theme-aether` from the AUR isn't updated anymore.

**Describe the solution you'd like**
You should change it to `lightdm-webkit-theme-aether-git` so that it is always up to date.

**Describe alternatives you've considered**
You should change it to `lightdm-webkit-theme-aether-git` so that it is always up to date.

**Comment by NoiSek** [comment]
The AUR package is deliberately not kept directly in sync with Git, as the master branch should not be considered stable at any time. At best a user tracking git directly would have an unstable experience, but at worst they would become unable to log into their systems. Users should be free to make their own decisions, but the package you've created is potentially quite harmful.

As it stands the existing AUR package corresponds to actual releases: https://github.com/NoiSek/Aether/releases

**Comment by GoDzM4TT3O** [comment]
Oh, ok. I just made it because the AUR package was flagged out of date. Anyway, closing this issue.
