### ISSUE TITLE
Remove the white ring around the avatar?

### ISSUE THREAD

**Issue by Jamesdawg1977** [NoiSek/Aether#81]
First, I love this theme so much. It's gorgeous, and almost perfect. My only problem is the white ring around the avatar picture in the login screen. Is there any way to remove it? Or at the very least change the color or center it? I searched through all the config but I couldn't find anything. Thank you so much in advance, and again, great work!

**Comment by clausmarian** [comment]
Open the settings menu of the theme, go to `General` and scroll down to `Avatar Visibility`, then uncheck `Background Enabled`. 
![Screenshot_2020-09-05_10-39-40](https://user-images.githubusercontent.com/58404164/92301546-000feb00-ef65-11ea-9796-89e0657e0975.png)

**Comment by NoiSek** [comment]
Thanks for answering this 👍
