### ISSUE TITLE
[BUG] There is no image of an astronaut or any other one

### ISSUE THREAD

**Issue by DestroyerXyz** [NoiSek/Aether#82]
**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Steps To Reproduce**

**Screenshots**

**Additional context**

**Comment by DestroyerXyz** [comment]
![Screenshot from 2020-08-31 12-05-29](https://user-images.githubusercontent.com/70191184/91689804-72a65280-eb82-11ea-9f8e-4a44801dbdf2.png)

**Comment by Morantxu** [comment]
Same here...

**Comment by Morantxu** [comment]
I solved it, see #14 !
