### ISSUE TITLE
Two dropdown boxes showing up for changing DE

### ISSUE THREAD

**Issue by DestroyerXyz** [NoiSek/Aether#83]
**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Steps To Reproduce**

**Screenshots**

**Additional context**

**Comment by DestroyerXyz** [comment]
![Screenshot from 2020-08-31 12-05-29](https://user-images.githubusercontent.com/70191184/91689756-602c1900-eb82-11ea-9623-863312738bc4.png)

**Comment by DaemonBeast** [comment]
I have also experienced this issue, specifically when I select GNOME like in the screenshot. The issue does not seem to occur when I select a different desktop environment (but does become buggy if I select GNOME before selecting a different desktop environment).

**Comment by rileyhawk1417** [comment]
Will the issue be fixed anytime soon?

**Comment by NoiSek** [comment]
A rewrite that incorporates the fix is much more likely, but the 2.0 I had on the horizon was killed by negative interactions with AUR users.

It'll happen eventually! But development is definitely in hiatus at the moment.

**Comment by rileyhawk1417** [comment]
All the best then, hopefully you can get back up on your feet 😄
