### ISSUE TITLE
I'd love a monitor config option

### ISSUE THREAD

**Issue by JohnH-312** [NoiSek/Aether#86]
As I understand this is *Supposed* to be a feature of the default lightdm but I can't get it working. I was unable to get any commands or scripts running to run xrandr --output _Monitor_Name_ --primary. This was supposed to work, but doesn't for some reason. 

I was hoping there would be a config option similar to "active-monitor=0" present in some lightdm-gtk themes, so i can get the greeter to display on my preferred monitor (even tho its plugged in to the secondary port because of cable types). 

As of now I have to deal with the login screen sideways on the wrong monitor, switch to a different theme, or not even use a display manager altogether. OR i could contact the lightdm devs and get help making the script actually run for display-setup-script=...

**Comment by NoiSek** [comment]
This is a question better directed to the upstream [webkit-greeter](https://github.com/Antergos/web-greeter) devs, given that this essentially a theme on top of a theme it has no real access to any of those lightdm configuration options.
