### ISSUE TITLE
Login Report

### ISSUE THREAD

**Issue by sajadshafi** [NoiSek/Aether#91]
It should Log in with out any problem

**Actual behavior**
Shows invalid password even when i enter correct one

**Comment by TraceM171** [comment]
Ok, I had the same problem, turns out that actual login won't work if you have window.__debug setted to true. Maybe you left it activated when changing some values like the suggested in [this comment](https://github.com/NoiSek/Aether/issues/75#issuecomment-597435275). Check that.

**Comment by NoiSek** [comment]
Closing this for now due to lack of information, it's hard to diagnose these issues without further detail. 

Please, follow the templates!
